### ISSUE TITLE
Editing tag breaks ALL data on pages using that tag.

### ISSUE THREAD

**Issue by Eaglef90** [usome/UmbracoTagManager#14]
In Umbraco 13 if I go into a tag set and change the "Tag Name" and save, any document that was using that tag has all the data in every property changed to "System.Collections.Generic.List`1[System.String]" This is for text-box, RTE, Tags, etc. If it was not a text-based property the value is lost (like muti-node picker or image picker)

**Comment by pasangtamang** [comment]
@Eaglef90 Thank you for the issue reporting. We will go through the issue and keep you updated.

**Comment by BishalTimalsina12** [comment]
@Eaglef90 

Thanks for bringing this to our attention! We've fixed the issue by implementing a solution that preserves data integrity when changing tag names in Umbraco 13. Now, properties like text-boxes and RTEs retain their values, preventing any loss of data

Please make sure to use the latest version of the [TagManager.1.0.4,]
(https://www.nuget.org/packages/TagManager/1.0.4) as these fixes have been implemented there.

If you have any further questions or encounter additional issues, feel free to reach out.

Best Regards,
